{{-
  if eq .Values.environment "local-development"
-}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: puppet-agent-volume
spec:
  capacity:
    storage: 1G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/puppet-agent/puppet/ssl
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lima-rancher-desktop

{{- end }}