version: '3.8'

services:
  puppet-server:
    image: puppet-server:latest
    hostname: puppet
    ports:
      - 8140:8140
    links:
      - puppet-db:puppetdb
  puppet-agent:
    image: puppet-agent:latest
    links:
      - "puppet-server:puppet"
    restart: always
  puppet-db:
    image: puppet-db:latest
    restart: always
  puppet-board:
    image: puppet-board:latest
    environment:
      - PUPPETDB_HOST=puppet-db
      - PUPPETDB_PORT=8080
      - PUPPETBOARD_URL_PREFIX=/puppetboard
      - DISPLAYED_METRICS=resources.total
    links:
      - puppet-db
    ports:
      - 8090:80
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    restart: always
    # Volume de persistência
